In [8]:
# Torch version
!python -c "import torch; print(torch.__version__)"

# Cuda version
!python -c "import torch; print(torch.version.cuda)"

2.6.0+cu124
12.4


In [9]:
import torch
torch.cuda.empty_cache()

In [10]:
# Uninstall
# !pip uninstall torch-scatter torch-sparse torch-cluster torch-spline-conv pyg-lib -y

In [11]:
# Update Torch
# !pip install torch==2.6.0 torchvision==0.21.0 torchaudio==2.6.0 --index-url https://download.pytorch.org/whl/cu124

In [12]:
# Install PyG (automatic)
# !pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-{torch.__version__}.html
# !pip install torch_geometric

In [13]:
# Verify instalation
import torch
import torch_geometric
import torch_scatter

print(torch.__version__)
print(torch.version.cuda)
print(torch.cuda.is_available())
print(torch_scatter.__version__)
print(torch_geometric.__version__)

2.6.0+cu124
12.4
True
2.1.2+pt26cu124
2.7.0


In [14]:
from model_PyG import *
from utils import *

In [8]:
import json
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F
import torch_geometric.transforms as T
import os
import umap

from mpl_toolkits.mplot3d import Axes3D
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from sklearn.metrics import silhouette_score
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import StandardScaler
from torch_geometric.data import InMemoryDataset, Data
from torch_geometric.utils import dense_to_sparse, negative_sampling
from torch.nn.functional import binary_cross_entropy_with_logits
from torch.optim import Adam

In [9]:
import torch_geometric
print(torch_geometric.__version__)

2.7.0


### Utils

In [10]:
def info(data):
	print("Validate:\t {}".format(data.validate(raise_on_error=True)))
	print("Num. nodes:\t {}".format(data.num_nodes))
	print("Num. edges:\t {}".format(data.num_edges))
	print("Num. features:\t {}".format(data.num_node_features))
	print("Has isolated:\t {}".format(data.has_isolated_nodes()))
	print("Has loops:\t {}".format(data.has_self_loops()))
	print("Is directed:\t {}".format(data.is_directed()))
	print("Is undirected:\t {}".format(data.is_undirected()))
	print("{}".format(data.edge_index))
	print("{}".format(data.x))
	print("{}".format(data.edge_attr))

def compute_num_neg_samples(edge_index, num_nodes, ratio):
	E = edge_index.size(1)
	max_neg = num_nodes * num_nodes - E
	return min(int(ratio * E), max_neg)

def neg_ratio_schedule(epoch, max_epoch):
	start = 5.0
	end = 1.0
	return start - (start - end) * (epoch / max_epoch)

class EarlyStopping:
	def __init__(self, patience=5, delta=0, warmup=5, verbose=False):
		self.patience = patience
		self.delta = delta
		self.warmup = warmup
		self.verbose = verbose
		self.best_loss = None
		self.no_improvement_count = 0
		self.stop_training = False
	
	def check_early_stop(self, loss, epoch):
		if epoch >= self.warmup:
			if self.best_loss is None or loss < self.best_loss - self.delta:
				self.best_loss = loss
				self.no_improvement_count = 0
			else:
				self.no_improvement_count += 1
				if self.no_improvement_count >= self.patience:
					self.stop_training = True
					if self.verbose:
						print("Stopping early as no improvement has been observed.")

### Parameters

In [11]:
file = open("exp.json")
experiment = json.load(file)
exp = experiment["exp"] # Change to static, e.g. "exp1"

file = open("experiments/output/{}/parameters.json".format(exp))
params = json.load(file)

print("Exp:\t\t", exp)

raw_data_file = params["raw_data_file"]
print("Raw data:\t", raw_data_file)

methods = params["methods"]
print("Methods:\t", methods)

apply_transformation = params["apply_transformation"]
print("Has transformation:", apply_transformation)

dimension = params["dimension"]
print("Dimension:\t", dimension)

groups_id = params["groups_id"]
print("Groups id:\t", groups_id)

subgroups_id = params["subgroups_id"]
print("Subgroups id:\t", subgroups_id)

cuda = params["cuda"]
print("Cuda:\t", cuda)

epochs = params["epochs"]
print("Epochs:\t", epochs)

lr = params["lr"]
print("Lr:\t", lr)

Exp:		 exp38
Raw data:	 Pablo_new_N_br_M_ar_p_42_format
Methods:	 ['t-gae']
Has transformation: False
Dimension:	 64
Groups id:	 ['disease']
Subgroups id:	 {'disease': ['2', '3', '4', '14', '15', '16']}
Cuda:	 0
Epochs:	 500
Lr:	 0.0001


In [12]:
# Remove
# groups_id = ["LSNB", "BC", "RCC", "BPH", "PD"] # "OSA" Memory issue
# groups_id = ["CKD-Severe", "LPRD"] # ["AR", "Health", "CKD-Mild", "CKD-Severe", "LPRD"]

### Setup

In [13]:
# Parameters models

dataset = exp
encoders = ["GIN"] # ["GIN", "GINE"] # ["GIN", "GINE"] # Change
device = torch.device(f"cuda:{cuda}" if torch.cuda.is_available() else "cpu")
# device = torch.device("cpu")

NUM_HIDDEN_LAYERS = 12
HIDDEN_DIM = [1024,1024,1024,1024,1024,1024,1024,1024,1024,1024,1024,1024,1024]
output_feature_size = dimension # 128
# lr = 0.001
# epochs = 100

In [14]:
# Create datasets (groups and subgroups)

list_train_set = []

for group_id in groups_id:
	train_set = []
	for subgroup_id in subgroups_id[group_id]:
		train_set.append("{}_{}".format(group_id, subgroup_id))
	list_train_set.append(train_set)
list_train_set

[['disease_2',
  'disease_3',
  'disease_4',
  'disease_14',
  'disease_15',
  'disease_16']]

### Create Data (PyG)

In [15]:
# Only for GIN
""" transform = Compose([
	# T.NormalizeFeatures(),
	T.ToUndirected(reduce="mean"),
	T.AddSelfLoops(fill_value=1.0),
	T.ToDevice(device)
]) """

# For GIN and GINE
transform = T.Compose([
	# T.NormalizeFeatures(),
	T.ToUndirected(reduce="mean"),
	T.AddSelfLoops(attr="edge_attr", fill_value="mean"),
	# T.AddLaplacianEigenvectorPE(k=3, attr_name=None, is_undirected=True),
	# T.AddRandomWalkPE(walk_length=8, attr_name=None),
	T.ToDevice(device)
])

In [16]:
print("Loading training datasets")

list_train_loader = []
# scaler = StandardScaler()

# features = [0, 1, 2, 4, 5] # Change
features = [0, 2, 4, 5] # Change (for Pablo)

for group_id in groups_id:
	train_loader = {}
	for subgroup_id in subgroups_id[group_id]:
		df_nodes = pd.read_csv(f"experiments/output/{exp}/preprocessing/graphs_data/nodes_{group_id}_{subgroup_id}.csv")
		# idx, id, mz, rt, 0, 1, 2, ...

		df_intensity = df_nodes.iloc[:, 4:]
		# 0, 1, 2, ...

		df_edges = pd.read_csv(f"experiments/output/{exp}/preprocessing/graphs_data/edges_{group_id}_{subgroup_id}.csv")
		# source, target, weight, subgroup

		# Node features
		""" mz = np.log10(df_nodes["mz"].values + 1e-8) # Log-transform m/z to stabilize scale differences
		rt = df_nodes["rt"].values
		rt = (rt - rt.mean()) / (rt.std() + 1e-8) # Z-score normalization for retention time (RT)

		intensity = df_intensity.values.astype(np.float32)
		intensity = intensity / (intensity.sum(axis=0, keepdims=True) + 1e-8)
		intensity_mean = intensity.mean(axis=1)

		intensity_std = intensity.std(axis=1)
		intensity_cv = intensity_std / (intensity_mean + 1e-8)
		intensity_cv = np.log1p(np.clip(intensity_cv, 0, 2.0))

		presence_ratio = (df_intensity > 0).mean(axis=1) # Acts as a reliability / confidence signal """

		# df_intensity = np.sign(df_intensity) * np.log10(np.abs(df_intensity) + 1e-8)

		mz = np.log10(df_nodes.iloc[:, 2].values + 1e-8)
		rt = df_nodes.iloc[:, 3].values
		rt = (rt - rt.mean()) / (rt.std() + 1e-8)
		intensity_mean = df_intensity.mean(axis=1).values
		intensity_std = df_intensity.std(axis=1).values
		intensity_cv = intensity_std / (intensity_mean + 1e-8)
		# presence_ratio = (df_intensity > 0).mean(axis=1)
		threshold = df_intensity.quantile(0.2).mean() # Change value
		presence_ratio = (df_intensity > threshold).mean(axis=1)

		x = np.stack([
				mz,             				# 0 physicochemical identity
				rt,								# 1 chromatographic alignment
				# np.log10(intensity_mean + 1e-8),# 2 global abundance
				intensity_mean,					# 2 global abundance
				intensity_std,  				# 3
				intensity_cv,   				# 4 robustness (anti-oversmoothing)
				presence_ratio  				# 5 reliability
			], axis=1)

		x = torch.tensor(x[:, features], dtype=torch.float) # [N, F]
		# x = torch.tensor(scaler.fit_transform(x.numpy())) # scaling

		# Edge index
		edge_index = torch.tensor(df_edges.iloc[:, [0, 1]].values.T, dtype=torch.long) # [2, E]

		# Edge attribute
		edge_weight = torch.tensor(df_edges.iloc[:, 2].values, dtype=torch.float) # [E]

		# edge_attr = edge_weight.view(-1, 1) # [E,1]
		edge_attr = torch.stack([
							edge_weight.abs(),        # strength
							torch.sign(edge_weight),  # direction (+1, -1)
							edge_weight ** 2          # nonlinearity
						], dim=1) # [E, 3]

		# Reduce number of edges
		""" mask = torch.abs(edge_weight) > 0.995
		edge_index = edge_index[:, mask]
		edge_attr  = edge_attr[mask] """

		data = Data(x=x, edge_index=edge_index.contiguous(), edge_attr=edge_attr)

		data = transform(data)
		# data = data.to(device)

		train_loader[f"{group_id}_{subgroup_id}"] = data
		info(data)

		test_pairs = None # No use
	list_train_loader.append(train_loader)

Loading training datasets
Validate:	 True
Num. nodes:	 5441
Num. edges:	 2963711
Num. features:	 4
Has isolated:	 False
Has loops:	 True
Is directed:	 False
Is undirected:	 True
tensor([[   0,    0,    0,  ..., 5438, 5439, 5440],
        [   1,    2,    3,  ..., 5438, 5439, 5440]], device='cuda:0')
tensor([[1.8451, 0.1605, 6.4632, 0.0482],
        [1.8455, 1.7362, 0.3676, 0.8193],
        [1.9348, 1.9209, 0.4934, 0.7108],
        ...,
        [2.4349, 1.7430, 0.3375, 0.8193],
        [2.3407, 1.5947, 0.4590, 0.6867],
        [2.6805, 0.8990, 1.5329, 0.2048]], device='cuda:0')
tensor([[0.3266, 1.0000, 0.1067],
        [0.3509, 1.0000, 0.1231],
        [0.2701, 1.0000, 0.0730],
        ...,
        [0.2674, 1.0000, 0.0715],
        [0.2761, 1.0000, 0.0762],
        [0.3011, 1.0000, 0.0911]], device='cuda:0')
Validate:	 True
Num. nodes:	 5443
Num. edges:	 2963713
Num. features:	 4
Has isolated:	 False
Has loops:	 True
Is directed:	 False
Is undirected:	 True
tensor([[   0,    0,    0,  ..

In [17]:
# Features details
pd.DataFrame(data.x.cpu().numpy()).describe()

,0,1,2,3
count,5438.000000,5438.000000,5438.000000,5438.000000
mean,2.296719,2.511971,0.503860,0.803768
std,0.187623,1.262899,3.635146,0.266979
min,1.845095,-0.955729,-107.109734,0.000000
25%,2.167572,1.569082,0.164318,0.622378
50%,2.305786,2.276172,0.315153,0.986014
75%,2.428454,3.370912,0.531224,1.000000
max,2.934873,6.366635,161.035660,1.000000


### Train

In [18]:
def fit_TGAE_subgraph(model, encoder, exp, group_id, subgroups_id, train_loader, train_set, no_samples, epochs, lr):
	list_loss = []

	optimizer = Adam(model.parameters(), lr=lr, weight_decay=5e-4)
	
	# Initialize early stopping
	patience = 10
	delta = 1e-4
	warmup = 10
	early_stopping = EarlyStopping(patience=patience, delta=delta, warmup=warmup, verbose=True)

	loop_obj = tqdm(range(1, epochs + 1))
	
	# Train mode
	model.train() # Set the model to training mode (enables dropout and BN updates)
	
	for epoch in loop_obj:
		loop_obj.set_description(f"Epoch: {epoch}")
		
		optimizer.zero_grad() # Reset accumulated gradients before backpropagation
		
		loss = torch.tensor(0.0, device=device)
		
		for ts in random.sample(train_set, k=len(train_set)): # shuffle train_set
			data = train_loader[ts]

			# Encoder
			if encoder == "GIN":
				z = model(data.x, data.edge_index)
				# z = F.normalize(z, dim=1)
			elif encoder == "GINE":
				z = model(data.x, data.edge_index, data.edge_attr)

			# Positive edges
			pos_edge_index = data.edge_index
			
			# Negative edges
			# option 1
			neg_edge_index = negative_sampling(
				edge_index=data.edge_index,
				num_nodes=z.size(0),
				num_neg_samples=pos_edge_index.size(1), # Change 2 to other value if needed
				method="sparse"
			)

			# option 2 Negative edges (dynamic)
			""" ratio = neg_ratio_schedule(epoch, epochs)
			num_neg = compute_num_neg_samples(
				edge_index=edge_index,
				num_nodes=z.size(0),
				ratio=ratio
			)
			neg_edge_index = negative_sampling(
				edge_index=edge_index,
				num_nodes=z.size(0),
				num_neg_samples=num_neg,
				method="sparse"
			) """
			
			# Decoder
			# option 1
			pos_logits = (z[pos_edge_index[0]] * z[pos_edge_index[1]]).sum(dim=1)
			neg_logits = (z[neg_edge_index[0]] * z[neg_edge_index[1]]).sum(dim=1)
			
			# option 2
			""" pos_logits = F.cosine_similarity(
				z[pos_edge_index[0]],
				z[pos_edge_index[1]],
				dim=1
			)
			neg_logits = F.cosine_similarity(
				z[neg_edge_index[0]],
				z[neg_edge_index[1]],
				dim=1
			) """

			# Loss
			pos_labels = torch.ones_like(pos_logits)
			neg_labels = torch.zeros_like(neg_logits)

			# option 1
			""" loss_pos = binary_cross_entropy_with_logits(pos_logits, pos_labels)
			loss_neg = binary_cross_entropy_with_logits(neg_logits, neg_labels)
			loss += loss_pos + loss_neg """

			# option 2
			# num_pos = pos_edge_index.size(1)
			# num_neg = neg_edge_index.size(1)
			# pos_weight = torch.tensor([num_neg / num_pos], device=device)
			logits = torch.cat([pos_logits, neg_logits], dim=0)
			labels = torch.cat([pos_labels, neg_labels], dim=0)
			loss_temp = F.binary_cross_entropy_with_logits(logits, labels) #, pos_weight=pos_weight) # with pos_weight
			loss += loss_temp
			
		loss = loss / no_samples
		loss.backward() # Compute gradients of the loss w.r.t. model parameters
		optimizer.step() # Update model parameters using computed gradients

		loop_obj.set_postfix_str(f"Loss: {loss.item():.4f}")
		list_loss.append(loss.item())

		# Check early stopping condition
		early_stopping.check_early_stop(loss.item(), epoch)
		if early_stopping.stop_training:
			print(f"Early stopping at epoch {epoch}")
			break
		# torch.cuda.empty_cache()
	# Evaluation (for others dataset)
	list_df_node_embeddings = []

	model.eval() # Set the model to evaluation mode (disables dropout and BN updates)
	with torch.no_grad():
		for subgroup_id in subgroups_id:

			# Get node embeddings
			data = train_loader[f"{group_id}_{subgroup_id}"]
			if encoder == "GIN":
				z = model(data.x, data.edge_index)
			elif encoder == "GINE":
				z = model(data.x, data.edge_index, data.edge_attr)
			
			df_node_embeddings = pd.DataFrame(z.cpu().numpy())
			df_node_embeddings["subgroup_id"] = [subgroup_id] * len(df_node_embeddings)
			
			# Get node ids to replace original Id
			df_nodes = pd.read_csv(f"experiments/output/{exp}/preprocessing/graphs_data/nodes_{group_id}_{subgroup_id}.csv")
			# idx,id,mz,rt,intensity_mean,intensity_cv
			df_node_embeddings.insert(0, "Id", df_nodes["id"].values)
			list_df_node_embeddings.append(df_node_embeddings)

		# Concat node embeddings
		df_node_embeddings_concat = pd.concat(list_df_node_embeddings, ignore_index=True)
		
		# Save node embeddings
		df_node_embeddings_concat.to_csv(f"experiments/output/{exp}/node_embeddings/{encoder}_{group_id}.csv", index=False)
	
	# Save loss
	np.save(f"experiments/output/{exp}/loss/{encoder}_{group_id}.npy", np.array(list_loss))

	del loss, z
	# torch.cuda.synchronize()
	torch.cuda.empty_cache()

In [1]:
list_train_set

NameError: name 'list_train_set' is not defined

In [20]:
list_train_loader

[{'disease_2': Data(x=[5441, 4], edge_index=[2, 2963711], edge_attr=[2963711, 3]),
  'disease_3': Data(x=[5443, 4], edge_index=[2, 2963713], edge_attr=[2963713, 3]),
  'disease_4': Data(x=[5430, 4], edge_index=[2, 2963700], edge_attr=[2963700, 3]),
  'disease_14': Data(x=[5444, 4], edge_index=[2, 2963714], edge_attr=[2963714, 3]),
  'disease_15': Data(x=[5431, 4], edge_index=[2, 2963701], edge_attr=[2963701, 3]),
  'disease_16': Data(x=[5438, 4], edge_index=[2, 2963708], edge_attr=[2963708, 3])}]

In [21]:
for encoder in encoders:
	for i, train_loader in enumerate(list_train_loader):
		np.random.seed(0)
		torch.manual_seed(0)
		torch.cuda.manual_seed(0)
		torch.cuda.manual_seed_all(0)
		torch.backends.cudnn.deterministic = True
		torch.backends.cudnn.benchmark = False

		group_id = groups_id[i]
		subgroups_id_ = subgroups_id[group_id]

		train_set = list_train_set[i]

		no_samples = len(train_set) # * (1 + 1)  # num datasets * num of samples by dataset 
		input_dim = train_loader[train_set[0]].num_node_features

		if encoder == "GIN":
			model = TGAE_GIN(NUM_HIDDEN_LAYERS,
						input_dim,
						HIDDEN_DIM,
						output_feature_size).to(device)
		elif encoder == "GINE":
			edge_dim = train_loader[train_set[0]].edge_attr.size(1)

			model = TGAE_GINE(NUM_HIDDEN_LAYERS,
						input_dim,
						HIDDEN_DIM,
						output_feature_size, edge_dim).to(device)

		print("Fitting model")
		print(encoder, dataset, train_set, lr, epochs, input_dim, output_feature_size, no_samples)

		fit_TGAE_subgraph(model, encoder, dataset, group_id, subgroups_id_, train_loader, train_set, no_samples, epochs, lr)

Fitting model
GIN exp38 ['disease_2', 'disease_3', 'disease_4', 'disease_14', 'disease_15', 'disease_16'] 0.0001 500 4 64 6


Epoch: 2:   0%|          | 1/500 [00:42<5:52:35, 42.40s/it, Loss: 1.1754]


OutOfMemoryError: CUDA out of memory. Tried to allocate 11.35 GiB. GPU 0 has a total capacity of 47.41 GiB of which 707.94 MiB is free. Including non-PyTorch memory, this process has 46.70 GiB memory in use. Of the allocated memory 34.24 GiB is allocated by PyTorch, and 12.15 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)